### ISSUE TITLE
v0.2 does not start on Firefox 54

### ISSUE THREAD

**Issue by ainola** [idlewan/vertigo-tabs#1] opened 2017-07-21 15:27 UTC
I realize that this is intended for FF 57+, but v0.1 would load on my Firefox 54 (archlinux) while the newest version doesn't seem to load.

If there's no intention to support <FF 57, maybe the supported version should be updated.

Thanks for all of your hard work! I'm really interested to see where this project goes.

**Comment by idlewan** [comment] 2017-07-22 13:01
Ah interesting, I might have a look.
I did most of my tests with firefox developer edition (beta 8 then 10), because 54 doesn't seem to use system font styling by default (font family, size and colors), so since 55 should be out in august I didn't want to spend time testing something that is going to fix itself automatically. I do use 54 for my main browser as well though.

However I'm not sure which changes I did between 0.1 and 0.2 would have affected 54 but not 55, so would be interesting to find that out.

**Comment by idlewan** [comment] 2017-07-24 16:06
I could not reproduce (Firefox 54.0.1 (64-bit) on Arch) with the v0.2 hosted on `addons.mozilla.org` .
The addon loads for me and works as expected (apart from the wrong font family and size used, which is fixed in 55).

Maybe the sidebar wasn't opened when you tried it? Or it could have closed itself when you didn't want it to? Any log present if you enable add-on debugging (`about:debugging`) and try to reload the add-on?

I don't think I can specify a supported version of firefox in the manifest or on AMO, it's automatic I think. Anyway, people who want to use it on an unsupported-by-me version are welcome to try, I won't stop them (it might even work).

**Closed by idlewan** 2017-07-24 16:06 UTC

**Comment by VegaDeftwing** [comment] 2017-09-03 14:24
I can't say what steps to reproduce, but I have the same issue, arch as well.

**Comment by ainola** [comment] 2017-09-03 14:26
It seemed to be something to do with the firefox profile: a fresh profile would work. I've also noticed that other webextension tree addons were not loading. So I imagine it's not this project's issue.

**Comment by idlewan** [comment] 2017-09-03 20:12
@VegaDeftwing Have you tried on Firefox 55? Should be in arch's packages.

**Comment by ainola** [comment] 2017-09-03 21:25
FWIW, I have tried it on FF 55, but with the AMO version rather than the arch version. The same issue presides.

**Comment by idlewan** [comment] 2017-09-03 21:28
The addon is only hosted on AMO, I was talking about Firefox v55 being in arch's packages (since the issue title was about 54, I assumed you had the problem on 54).

Is it just a case of the sidebar being hidden, and clicking on the sidebar button and choosing Vertigo Tabs from the list ?

**Comment by ainola** [comment] 2017-09-03 21:40
> Is it just a case of the sidebar being hidden, and clicking on the sidebar button and choosing Vertigo Tabs from the list ?

Er, I think that was it. :( I didn't know about that sidebar button, but adding that to the toolbar and then selecting 'vertigo-tabs' did work.

@VegaDeftwing, is this your issue, too?
